dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
services:
  - postgresql
script: bundle exec rake test
before_install:
  - createdb pgslice_test
notifications:
  email:
    on_success: never
    on_failure: change
matrix:
  include:
    - name: "Postgres 9.6"
      addons:
        postgresql: "9.6"
    - name: "Postgres 10"
      addons:
        postgresql: "10"
