language: ruby
rvm: 2.4.1
cache: bundler
sudo: false
script: bundle exec rake test
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database pgslice_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
